/**
 * House of Madhu Das Gupta — Product Catalog
 * Static data source for PLPs / PDP / cart / designer showrooms
 */
window.MDG_PRODUCTS = [
  /* ===== EXISTING — keep ids stable (non-Sakshi) ===== */
  {
    id: "bridal-royal-crimson",
    slug: "royal-crimson-bridal-lehenga",
    collection: "Bridal",
    designerId: "seema-gujral",
    name: "Royal Crimson Bridal Lehenga",
    price: 145000,
    image: "bridal.jpg",
    description: "Handcrafted zardozi embroidery on luxurious silk — a statement bridal lehenga tailored for your wedding day.",
    fabric: "Pure Silk",
    embroidery: "Hand Zardozi",
    delivery: "4–6 Weeks",
    customization: "Available"
  },
  {
    id: "bridal-ivory-pearl",
    slug: "ivory-pearl-bridal-lehenga",
    collection: "Bridal",
    designerId: "nitika-gujral",
    name: "Ivory Pearl Bridal Lehenga",
    price: 128000,
    image: "bridal.jpg",
    description: "Soft ivory silk with pearl and sequin work — ethereal bridal elegance with a modern silhouette.",
    fabric: "Silk Organza",
    embroidery: "Pearl & Sequin",
    delivery: "4–6 Weeks",
    customization: "Available"
  },
  {
    id: "bridal-maroon-heritage",
    slug: "maroon-heritage-bridal-set",
    collection: "Bridal",
    designerId: "ridhi-mehra",
    name: "Maroon Heritage Bridal Set",
    price: 165000,
    image: "bridal.jpg",
    description: "Deep maroon heritage bridal set with dense traditional motifs and a dramatic flared lehenga.",
    fabric: "Banarasi Silk",
    embroidery: "Traditional Motifs",
    delivery: "5–7 Weeks",
    customization: "Available"
  },
  {
    id: "couture-cocktail-glam",
    slug: "midnight-cocktail-gown",
    collection: "Couture",
    designerId: "riyaz-gangji-libas",
    name: "Midnight Cocktail Gown",
    price: 89000,
    image: "cocktail.JPG",
    description: "Sculpted cocktail couture with dramatic draping — made for red-carpet evenings and private soirées.",
    fabric: "Satin Crepe",
    embroidery: "Crystal Embellishment",
    delivery: "3–5 Weeks",
    customization: "Available"
  },
  {
    id: "couture-gold-drape",
    slug: "gold-drape-couture-gown",
    collection: "Couture",
    designerId: "riyaz-gangji-libas",
    name: "Gold Drape Couture Gown",
    price: 112000,
    image: "evening.jpg",
    description: "Fluid gold-toned draping with couture finishing — a bespoke masterpiece for exclusive occasions.",
    fabric: "Tissue Silk",
    embroidery: "Metallic Threadwork",
    delivery: "4–6 Weeks",
    customization: "Available"
  },
  {
    id: "couture-black-statement",
    slug: "noir-statement-couture",
    collection: "Couture",
    designerId: "gopi-vaid",
    name: "Noir Statement Couture",
    price: 98000,
    image: "cocktail.JPG",
    description: "Bold black couture silhouette with refined structure and hand-finished detailing.",
    fabric: "Silk Dupion",
    embroidery: "Minimal Gold Accents",
    delivery: "3–5 Weeks",
    customization: "Available"
  },
  {
    id: "sherwani-ivory-royal",
    slug: "ivory-royal-sherwani",
    collection: "Sherwani",
    designerId: "punit-arora",
    name: "Ivory Royal Sherwani",
    price: 85000,
    image: "Sherwani.jpg",
    description: "Elegant handcrafted sherwani tailored for modern royalty with premium fabric and intricate embroidery.",
    fabric: "Premium Silk Blend",
    embroidery: "Handcrafted",
    delivery: "3–5 Weeks",
    customization: "Available"
  },
  {
    id: "sherwani-midnight-nawab",
    slug: "midnight-nawab-sherwani",
    collection: "Sherwani",
    designerId: "punit-arora",
    name: "Midnight Nawab Sherwani",
    price: 95000,
    image: "Sherwani.jpg",
    description: "Deep midnight blue sherwani with regal buttons and subtle embroidery for a commanding presence.",
    fabric: "Raw Silk",
    embroidery: "Subtle Threadwork",
    delivery: "3–5 Weeks",
    customization: "Available"
  },
  {
    id: "sherwani-gold-bandhgala",
    slug: "gold-bandhgala-sherwani",
    collection: "Sherwani",
    designerId: "punit-arora",
    name: "Gold Bandhgala Sherwani",
    price: 78000,
    image: "Sherwani.jpg",
    description: "Classic bandhgala sherwani in warm gold tones — refined, ceremonial, and endlessly wearable.",
    fabric: "Brocade Silk",
    embroidery: "Gold Zari",
    delivery: "3–4 Weeks",
    customization: "Available"
  },
  {
    id: "evening-velvet-noir",
    slug: "velvet-noir-evening-gown",
    collection: "Evening",
    designerId: "kalista",
    name: "Velvet Noir Evening Gown",
    price: 72000,
    image: "evening.jpg",
    description: "Statement evening gown with velvet depth and a sculpted waist — designed for unforgettable nights.",
    fabric: "Velvet",
    embroidery: "Subtle Beading",
    delivery: "3–4 Weeks",
    customization: "Available"
  },
  {
    id: "evening-champagne-flare",
    slug: "champagne-flare-evening",
    collection: "Evening",
    designerId: "dolly-j",
    name: "Champagne Flare Evening Dress",
    price: 68000,
    image: "evening.jpg",
    description: "Champagne flare silhouette with soft shimmer — refined luxury for cocktail and formal evenings.",
    fabric: "Georgette",
    embroidery: "Sequin Cascade",
    delivery: "3–4 Weeks",
    customization: "Available"
  },
  {
    id: "evening-emerald-drape",
    slug: "emerald-drape-evening",
    collection: "Evening",
    designerId: "gopi-vaid",
    name: "Emerald Drape Evening Wear",
    price: 75000,
    image: "cocktail.JPG",
    description: "Rich emerald drape evening wear with contemporary cuts and timeless sophistication.",
    fabric: "Crepe Silk",
    embroidery: "Tone-on-Tone",
    delivery: "3–5 Weeks",
    customization: "Available"
  },
  {
    id: "resort-ivory-flow",
    slug: "ivory-flow-resort-dress",
    collection: "Resort",
    designerId: "dolly-j",
    name: "Ivory Flow Resort Dress",
    price: 45000,
    image: "resort.JPG",
    description: "Flowing ivory resort dress with soft structure — timeless ease for travel and leisure.",
    fabric: "Chiffon",
    embroidery: "Delicate Lace Trim",
    delivery: "2–4 Weeks",
    customization: "Available"
  },
  {
    id: "sg-rose-gold-lehenga",
    slug: "seema-rose-gold-lehenga",
    collection: "Bridal",
    designerId: "seema-gujral",
    name: "Rose Gold Bridal Lehenga",
    price: 158000,
    image: "bridal.jpg",
    description: "Rose-gold zari on blush silk — Seema Gujral’s signature bridal opulence for the modern wedding.",
    fabric: "Pure Silk",
    embroidery: "Rose Gold Zari",
    delivery: "5–7 Weeks",
    customization: "Available"
  },
  {
    id: "sg-emerald-bridal",
    slug: "seema-emerald-bridal",
    collection: "Bridal",
    designerId: "seema-gujral",
    name: "Emerald Heritage Bridal",
    price: 172000,
    image: "bridal.jpg",
    description: "Jewel-toned emerald bridal with dense heritage motifs and a dramatic flare.",
    fabric: "Banarasi Silk",
    embroidery: "Heritage Motifs",
    delivery: "5–7 Weeks",
    customization: "Available"
  },
  {
    id: "rm-anarkali-bloom",
    slug: "ridhi-anarkali-bloom",
    collection: "Couture",
    designerId: "ridhi-mehra",
    name: "Bloom Anarkali",
    price: 72000,
    image: "cocktail.JPG",
    description: "Romantic floral anarkali with soft volume — Ridhi Mehra’s festive signature.",
    fabric: "Georgette",
    embroidery: "Floral Sequin",
    delivery: "3–4 Weeks",
    customization: "Available"
  },
  {
    id: "rm-festive-sharara",
    slug: "ridhi-festive-sharara",
    collection: "Evening",
    designerId: "ridhi-mehra",
    name: "Festive Sharara Set",
    price: 65000,
    image: "evening.jpg",
    description: "Light festive sharara with delicate embroidery — perfect for sangeet and cocktail nights.",
    fabric: "Chiffon",
    embroidery: "Thread & Sequin",
    delivery: "3–4 Weeks",
    customization: "Available"
  },
  {
    id: "mkc-sculpted-saree",
    slug: "mukti-sculpted-saree",
    collection: "Couture",
    designerId: "mukti-and-kavith-casa",
    name: "Sculpted Drape Saree",
    price: 118000,
    image: "evening.jpg",
    description: "Architectural saree drape with structured blouse — Mukti & Kavith Casa’s couture language.",
    fabric: "Tissue Silk",
    embroidery: "Minimal Crystal",
    delivery: "4–6 Weeks",
    customization: "Available"
  },
  {
    id: "mkc-ivory-cape",
    slug: "mukti-ivory-cape",
    collection: "Couture",
    designerId: "mukti-and-kavith-casa",
    name: "Ivory Cape Ensemble",
    price: 125000,
    image: "cocktail.JPG",
    description: "Dramatic ivory cape over a sleek gown base — red-carpet ready.",
    fabric: "Crepe Silk",
    embroidery: "Pearl Edge",
    delivery: "4–5 Weeks",
    customization: "Available"
  },
  {
    id: "mkc-noir-gown",
    slug: "mukti-noir-gown",
    collection: "Evening",
    designerId: "mukti-and-kavith-casa",
    name: "Noir Sculpted Gown",
    price: 109000,
    image: "evening.jpg",
    description: "Black sculpted gown with clean lines and couture finishing.",
    fabric: "Satin",
    embroidery: "Tone-on-Tone",
    delivery: "3–5 Weeks",
    customization: "Available"
  },
  {
    id: "kalista-crystal-slip",
    slug: "kalista-crystal-slip",
    collection: "Evening",
    designerId: "kalista",
    name: "Crystal Slip Gown",
    price: 82000,
    image: "cocktail.JPG",
    description: "Sleek slip silhouette with crystal cascade — Kalista’s statement evening piece.",
    fabric: "Satin Crepe",
    embroidery: "Crystal Cascade",
    delivery: "3–4 Weeks",
    customization: "Available"
  },
  {
    id: "kalista-midnight-cape",
    slug: "kalista-midnight-cape",
    collection: "Evening",
    designerId: "kalista",
    name: "Midnight Cape Dress",
    price: 88000,
    image: "evening.jpg",
    description: "Midnight cape over a fitted dress — modern drama for soirées.",
    fabric: "Velvet & Crepe",
    embroidery: "Crystal Edge",
    delivery: "3–5 Weeks",
    customization: "Available"
  },
  {
    id: "gv-pearl-jacket",
    slug: "gopi-pearl-jacket",
    collection: "Couture",
    designerId: "gopi-vaid",
    name: "Pearl Embellished Jacket Set",
    price: 92000,
    image: "cocktail.JPG",
    description: "Fluid drape with pearl-jacket overlay — Gopi Vaid’s elevated fusion look.",
    fabric: "Silk Crepe",
    embroidery: "Pearl Work",
    delivery: "3–5 Weeks",
    customization: "Available"
  },
  {
    id: "pa-indigo-bandhgala",
    slug: "punit-indigo-bandhgala",
    collection: "Sherwani",
    designerId: "punit-arora",
    name: "Indigo Bandhgala",
    price: 72000,
    image: "Sherwani.jpg",
    description: "Deep indigo bandhgala with subtle zari — Punit Arora’s contemporary ceremonial cut.",
    fabric: "Raw Silk",
    embroidery: "Subtle Zari",
    delivery: "3–4 Weeks",
    customization: "Available"
  },
  {
    id: "dj-coral-kaftan",
    slug: "dolly-coral-kaftan",
    collection: "Resort",
    designerId: "dolly-j",
    name: "Coral Resort Kaftan",
    price: 38000,
    image: "resort.JPG",
    description: "Soft coral kaftan with light embroidery — Dolly J’s playful resort luxury.",
    fabric: "Linen Silk",
    embroidery: "Light Threadwork",
    delivery: "2–3 Weeks",
    customization: "Available"
  },
  {
    id: "ng-blush-lehenga",
    slug: "nitika-blush-lehenga",
    collection: "Bridal",
    designerId: "nitika-gujral",
    name: "Blush Pearl Lehenga",
    price: 118000,
    image: "bridal.jpg",
    description: "Soft blush bridal with pearl scatter — Nitika Gujral’s quiet luxury.",
    fabric: "Organza Silk",
    embroidery: "Pearl Scatter",
    delivery: "4–6 Weeks",
    customization: "Available"
  },
  {
    id: "ng-silver-sharara",
    slug: "nitika-silver-sharara",
    collection: "Bridal",
    designerId: "nitika-gujral",
    name: "Silver Festive Sharara",
    price: 98000,
    image: "bridal.jpg",
    description: "Silver-toned festive sharara with delicate beadwork for pre-wedding events.",
    fabric: "Net & Silk",
    embroidery: "Silver Beading",
    delivery: "4–5 Weeks",
    customization: "Available"
  },
  {
    id: "rgl-zardozi-lehenga",
    slug: "riyaz-zardozi-lehenga",
    collection: "Bridal",
    designerId: "riyaz-gangji-libas",
    name: "Heritage Zardozi Lehenga",
    price: 185000,
    image: "bridal.jpg",
    description: "Hand zardozi bridal lehenga — Riyaz Gangji Libas signature craftsmanship.",
    fabric: "Pure Silk",
    embroidery: "Hand Zardozi",
    delivery: "6–8 Weeks",
    customization: "Available"
  },
  {
    id: "rgl-velvet-sherwani",
    slug: "riyaz-velvet-sherwani",
    collection: "Sherwani",
    designerId: "riyaz-gangji-libas",
    name: "Velvet Royal Sherwani",
    price: 105000,
    image: "Sherwani.jpg",
    description: "Velvet sherwani with gold accents — ceremonial grandeur from Riyaz Gangji Libas.",
    fabric: "Velvet",
    embroidery: "Gold Accents",
    delivery: "4–6 Weeks",
    customization: "Available"
  },

  /* ===== SAKSHI BINDRA — 35 unique-image showroom pieces ===== */
  {
    id: "sb-ivory-aura-bridal",
    slug: "ivory-aura-bridal-lehenga",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Ivory Aura Bridal Lehenga",
    price: 185000,
    image: "products/sakshi/sb-01.jpg",
    description: "Luminous ivory bridal lehenga with cascading pearl and zari aura — crafted for the mandap with a modern flare and heirloom finish.",
    fabric: "Pure Silk Organza",
    embroidery: "Pearl & Zari Aura",
    delivery: "5–7 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-blush-heritage-bridal",
    slug: "blush-heritage-bridal-set",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Blush Heritage Bridal Set",
    price: 168000,
    image: "products/sakshi/sb-02.jpg",
    description: "Soft blush heritage bridal with dense traditional motifs and a sculpted blouse — quiet luxury for the contemporary bride.",
    fabric: "Banarasi Silk",
    embroidery: "Heritage Motifs",
    delivery: "5–7 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-crimson-veil-lehenga",
    slug: "crimson-veil-bridal-lehenga",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Crimson Veil Bridal Lehenga",
    price: 225000,
    image: "products/sakshi/sb-03.jpg",
    description: "Deep crimson bridal lehenga with veiled dupatta drama and hand zardozi — a statement for pheras and grand receptions.",
    fabric: "Pure Silk",
    embroidery: "Hand Zardozi",
    delivery: "6–8 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-rose-mandap-lehenga",
    slug: "rose-mandap-bridal-lehenga",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Rose Mandap Lehenga",
    price: 198000,
    image: "products/sakshi/sb-04.jpg",
    description: "Rose-gold bridal lehenga with sculpted flare and soft shimmer — made for mandap light and evening pheras.",
    fabric: "Tissue Silk",
    embroidery: "Rose Gold Zari",
    delivery: "5–7 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-marigold-royal-set",
    slug: "marigold-royal-bridal-set",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Marigold Royal Bridal Set",
    price: 210000,
    image: "products/sakshi/sb-05.jpg",
    description: "Marigold-gold bridal set with dense surface work and regal volume — festival-to-wedding grandeur.",
    fabric: "Raw Silk",
    embroidery: "Gold Zardozi",
    delivery: "6–8 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-pearl-cascade-lehenga",
    slug: "pearl-cascade-bridal-lehenga",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Pearl Cascade Bridal Lehenga",
    price: 175000,
    image: "products/sakshi/sb-06.jpg",
    description: "Ivory-pearl cascade lehenga with delicate beadfall and a soft contemporary silhouette.",
    fabric: "Silk Organza",
    embroidery: "Pearl Cascade",
    delivery: "5–6 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-velvet-pheras-gown",
    slug: "velvet-pheras-bridal-gown",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Velvet Pheras Bridal Gown",
    price: 155000,
    image: "products/sakshi/sb-07.jpg",
    description: "Fusion bridal gown in deep velvet with lehenga-inspired flare — modern pheras drama.",
    fabric: "Velvet & Silk",
    embroidery: "Crystal Edge",
    delivery: "4–6 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-champagne-vows-lehenga",
    slug: "champagne-vows-bridal-lehenga",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Champagne Vows Lehenga",
    price: 162000,
    image: "products/sakshi/sb-08.jpg",
    description: "Champagne bridal lehenga with soft metallic threadwork — luminous for daytime and candlelit vows.",
    fabric: "Georgette Silk",
    embroidery: "Metallic Threadwork",
    delivery: "5–7 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-heirloom-scarlet",
    slug: "heirloom-scarlet-bridal",
    collection: "Bridal",
    designerId: "sakshi-bindra",
    name: "Heirloom Scarlet Bridal",
    price: 250000,
    image: "products/sakshi/sb-09.jpg",
    description: "Signature scarlet bridal with museum-grade hand embroidery — the house’s ultimate wedding statement.",
    fabric: "Pure Banarasi Silk",
    embroidery: "Heirloom Hand Embroidery",
    delivery: "7–9 Weeks",
    customization: "Available",
    occasion: "Wedding"
  },
  {
    id: "sb-midnight-muse-cocktail",
    slug: "midnight-muse-cocktail-gown",
    collection: "Couture",
    designerId: "sakshi-bindra",
    name: "Midnight Muse Cocktail Gown",
    price: 98000,
    image: "products/sakshi/sb-10.jpg",
    description: "Sculpted midnight cocktail gown with crystal edge and dramatic hem — party glamour with couture restraint.",
    fabric: "Satin Crepe",
    embroidery: "Crystal Edge",
    delivery: "3–5 Weeks",
    customization: "Available",
    occasion: "Cocktail"
  },
  {
    id: "sb-champagne-hour-slip",
    slug: "champagne-hour-slip-dress",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Champagne Hour Slip Dress",
    price: 78000,
    image: "products/sakshi/sb-11.jpg",
    description: "Liquid champagne slip with soft shimmer and bias drape — effortless cocktail elegance.",
    fabric: "Satin",
    embroidery: "Sequin Cascade",
    delivery: "3–4 Weeks",
    customization: "Available",
    occasion: "Cocktail"
  },
  {
    id: "sb-ruby-soiree-gown",
    slug: "ruby-soiree-cocktail-gown",
    collection: "Couture",
    designerId: "sakshi-bindra",
    name: "Ruby Soirée Cocktail Gown",
    price: 89000,
    image: "products/sakshi/sb-12.jpg",
    description: "Jewel ruby cocktail gown with structured bodice and fluid skirt — designed to own the room.",
    fabric: "Silk Dupion",
    embroidery: "Tone-on-Tone Beading",
    delivery: "3–5 Weeks",
    customization: "Available",
    occasion: "Cocktail"
  },
  {
    id: "sb-onyx-party-column",
    slug: "onyx-party-column-gown",
    collection: "Couture",
    designerId: "sakshi-bindra",
    name: "Onyx Party Column",
    price: 92000,
    image: "products/sakshi/sb-13.jpg",
    description: "Sleek onyx column with high slit and crystal spine — cocktail nights and private clubs.",
    fabric: "Crepe Satin",
    embroidery: "Crystal Spine",
    delivery: "3–4 Weeks",
    customization: "Available",
    occasion: "Cocktail"
  },
  {
    id: "sb-blush-disco-mini",
    slug: "blush-disco-cocktail-mini",
    collection: "Couture",
    designerId: "sakshi-bindra",
    name: "Blush Disco Cocktail Mini",
    price: 58000,
    image: "products/sakshi/sb-14.jpg",
    description: "Playful blush mini with sequin scatter — dance-floor ready with refined finishing.",
    fabric: "Georgette",
    embroidery: "Sequin Scatter",
    delivery: "2–4 Weeks",
    customization: "Available",
    occasion: "Cocktail"
  },
  {
    id: "sb-emerald-afterparty",
    slug: "emerald-afterparty-dress",
    collection: "Couture",
    designerId: "sakshi-bindra",
    name: "Emerald Afterparty Dress",
    price: 72000,
    image: "products/sakshi/sb-15.jpg",
    description: "Rich emerald cocktail dress with sculpted waist and soft flare — from dinner to afterparty.",
    fabric: "Silk Crepe",
    embroidery: "Subtle Beading",
    delivery: "3–4 Weeks",
    customization: "Available",
    occasion: "Cocktail"
  },
  {
    id: "sb-silver-spark-gown",
    slug: "silver-spark-cocktail-gown",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Silver Spark Cocktail Gown",
    price: 105000,
    image: "products/sakshi/sb-16.jpg",
    description: "Silver metallic cocktail gown with controlled volume — red-carpet energy for soirées.",
    fabric: "Metallic Tissue",
    embroidery: "Silver Sequin",
    delivery: "3–5 Weeks",
    customization: "Available",
    occasion: "Cocktail"
  },
  {
    id: "sb-noir-cape-cocktail",
    slug: "noir-cape-cocktail-set",
    collection: "Couture",
    designerId: "sakshi-bindra",
    name: "Noir Cape Cocktail Set",
    price: 118000,
    image: "products/sakshi/sb-17.jpg",
    description: "Black cocktail set with detachable cape — architectural drama for elevated parties.",
    fabric: "Crepe & Organza",
    embroidery: "Minimal Crystal",
    delivery: "4–5 Weeks",
    customization: "Available",
    occasion: "Cocktail"
  },
  {
    id: "sb-noir-riviera-gown",
    slug: "noir-riviera-evening-gown",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Noir Riviera Evening Gown",
    price: 112000,
    image: "products/sakshi/sb-18.jpg",
    description: "Black Riviera evening gown with architectural drape and velvet depth — formal nights and private dinners.",
    fabric: "Velvet & Crepe",
    embroidery: "Minimal Crystal",
    delivery: "4–5 Weeks",
    customization: "Available",
    occasion: "Evening"
  },
  {
    id: "sb-gold-hour-saree",
    slug: "gold-hour-drape-saree",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Gold Hour Drape Saree",
    price: 95000,
    image: "products/sakshi/sb-19.jpg",
    description: "Gold-hour tissue saree with couture blouse and fluid drape — formal evening radiance.",
    fabric: "Tissue Silk",
    embroidery: "Metallic Threadwork",
    delivery: "3–5 Weeks",
    customization: "Available",
    occasion: "Evening"
  },
  {
    id: "sb-sapphire-opera-gown",
    slug: "sapphire-opera-evening-gown",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Sapphire Opera Gown",
    price: 128000,
    image: "products/sakshi/sb-20.jpg",
    description: "Deep sapphire opera gown with structured bodice and train — gala and awards evenings.",
    fabric: "Satin",
    embroidery: "Sapphire Beading",
    delivery: "4–6 Weeks",
    customization: "Available",
    occasion: "Evening"
  },
  {
    id: "sb-ivory-moon-gown",
    slug: "ivory-moon-evening-gown",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Ivory Moon Evening Gown",
    price: 108000,
    image: "products/sakshi/sb-21.jpg",
    description: "Ivory evening gown with soft moonlit shimmer and clean couture lines.",
    fabric: "Silk Satin",
    embroidery: "Pearl Edge",
    delivery: "3–5 Weeks",
    customization: "Available",
    occasion: "Evening"
  },
  {
    id: "sb-bronze-drape-saree",
    slug: "bronze-drape-evening-saree",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Bronze Drape Evening Saree",
    price: 88000,
    image: "products/sakshi/sb-22.jpg",
    description: "Bronze evening saree with contemporary blouse and fluid pallu — formal dinners and receptions.",
    fabric: "Crepe Silk",
    embroidery: "Bronze Zari",
    delivery: "3–4 Weeks",
    customization: "Available",
    occasion: "Evening"
  },
  {
    id: "sb-velvet-gala-cape",
    slug: "velvet-gala-cape-gown",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Velvet Gala Cape Gown",
    price: 135000,
    image: "products/sakshi/sb-23.jpg",
    description: "Velvet gala gown with sweeping cape — theatrical evening presence with refined craft.",
    fabric: "Velvet",
    embroidery: "Crystal Collar",
    delivery: "4–6 Weeks",
    customization: "Available",
    occasion: "Evening"
  },
  {
    id: "sb-smoke-column-gown",
    slug: "smoke-column-evening-gown",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Smoke Column Evening Gown",
    price: 99000,
    image: "products/sakshi/sb-24.jpg",
    description: "Smoke-grey column gown with subtle sheen — understated formal power.",
    fabric: "Crepe",
    embroidery: "Tone-on-Tone",
    delivery: "3–5 Weeks",
    customization: "Available",
    occasion: "Evening"
  },
  {
    id: "sb-aurora-beaded-gown",
    slug: "aurora-beaded-evening-gown",
    collection: "Evening",
    designerId: "sakshi-bindra",
    name: "Aurora Beaded Evening Gown",
    price: 145000,
    image: "products/sakshi/sb-25.jpg",
    description: "Aurora-inspired beaded evening gown with cascading light — statement formalwear.",
    fabric: "Net & Silk",
    embroidery: "Full Beading",
    delivery: "5–7 Weeks",
    customization: "Available",
    occasion: "Evening"
  },
  {
    id: "sb-soft-power-linen",
    slug: "soft-power-linen-coord",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Soft Power Linen Co-ord",
    price: 42000,
    image: "products/sakshi/sb-26.jpg",
    description: "Elevated linen co-ord with clean tailoring — daywear that reads polished from brunch to gallery openings.",
    fabric: "Premium Linen",
    embroidery: "Minimal Tone-on-Tone",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Casual"
  },
  {
    id: "sb-city-muse-kurta",
    slug: "city-muse-kurta-set",
    collection: "Couture",
    designerId: "sakshi-bindra",
    name: "City Muse Kurta Set",
    price: 48000,
    image: "products/sakshi/sb-27.jpg",
    description: "Sleek kurta set with refined embroidery and urban ease — elevated city dressing.",
    fabric: "Cotton Silk",
    embroidery: "Subtle Threadwork",
    delivery: "2–4 Weeks",
    customization: "Available",
    occasion: "Casual"
  },
  {
    id: "sb-ivory-day-kaftan",
    slug: "ivory-day-kaftan",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Ivory Day Kaftan",
    price: 36000,
    image: "products/sakshi/sb-28.jpg",
    description: "Fluid ivory day kaftan with light structure — effortless luxury for travel and leisure.",
    fabric: "Linen Silk",
    embroidery: "Light Embroidery",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Casual"
  },
  {
    id: "sb-sage-lounge-set",
    slug: "sage-lounge-coord-set",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Sage Lounge Co-ord",
    price: 32000,
    image: "products/sakshi/sb-29.jpg",
    description: "Sage lounge co-ord with soft volume and polished seams — weekend ease, elevated.",
    fabric: "Cotton",
    embroidery: "Minimal",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Casual"
  },
  {
    id: "sb-sand-shirt-dress",
    slug: "sand-shirt-dress",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Sand Shirt Dress",
    price: 28000,
    image: "products/sakshi/sb-30.jpg",
    description: "Sand-toned shirt dress with clean collar and soft belt — everyday chic with couture finish.",
    fabric: "Cotton Poplin",
    embroidery: "None",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Casual"
  },
  {
    id: "sb-navy-utility-set",
    slug: "navy-utility-coord",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Navy Utility Co-ord",
    price: 38000,
    image: "products/sakshi/sb-31.jpg",
    description: "Navy utility co-ord with tailored lines — modern casual power dressing.",
    fabric: "Linen Blend",
    embroidery: "Minimal Contrast",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Casual"
  },
  {
    id: "sb-garden-party-kaftan",
    slug: "garden-party-kaftan",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Garden Party Kaftan",
    price: 45000,
    image: "products/sakshi/sb-32.jpg",
    description: "Fluid garden-party kaftan with light shimmer — made for lawn lunches and destination afternoons.",
    fabric: "Linen Silk",
    embroidery: "Light Sequin Scatter",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Outdoor"
  },
  {
    id: "sb-sunlit-resort-set",
    slug: "sunlit-resort-set",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Sunlit Resort Set",
    price: 52000,
    image: "products/sakshi/sb-33.jpg",
    description: "Sunlit resort co-ord with soft draping — destination-ready from poolside to sunset dinner.",
    fabric: "Cotton Silk",
    embroidery: "Minimal Print Accents",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Outdoor"
  },
  {
    id: "sb-meadow-picnic-dress",
    slug: "meadow-picnic-dress",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Meadow Picnic Dress",
    price: 24000,
    image: "products/sakshi/sb-34.jpg",
    description: "Light meadow dress with breezy flare — outdoor brunches and destination days.",
    fabric: "Cotton Voile",
    embroidery: "Delicate Lace Trim",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Outdoor"
  },
  {
    id: "sb-coastal-breeze-set",
    slug: "coastal-breeze-coord",
    collection: "Resort",
    designerId: "sakshi-bindra",
    name: "Coastal Breeze Co-ord",
    price: 18000,
    image: "products/sakshi/sb-35.jpg",
    description: "Coastal breeze co-ord in breathable fabric — resort mornings and open-air evenings.",
    fabric: "Linen",
    embroidery: "Minimal",
    delivery: "2–3 Weeks",
    customization: "Available",
    occasion: "Outdoor"
  }
];

window.MDG_formatPrice = function (n) {
  return "₹" + Number(n).toLocaleString("en-IN");
};

window.MDG_getProduct = function (idOrSlug) {
  if (!idOrSlug) return null;
  var key = String(idOrSlug).toLowerCase();
  return (window.MDG_PRODUCTS || []).find(function (p) {
    return p.id.toLowerCase() === key || p.slug.toLowerCase() === key;
  }) || null;
};

window.MDG_getByCollection = function (name) {
  var n = String(name || "").toLowerCase();
  return (window.MDG_PRODUCTS || []).filter(function (p) {
    return p.collection.toLowerCase() === n;
  });
};

window.MDG_getByDesigner = function (designerId) {
  var key = String(designerId || "").toLowerCase();
  return (window.MDG_PRODUCTS || []).filter(function (p) {
    return String(p.designerId || "").toLowerCase() === key;
  });
};
